### ISSUE TITLE
Preference Menu is Empty

### ISSUE THREAD

**Issue by keepersdungeon** [StarCitizenTools/mediawiki-skins-Citizen#832]
After upgrading to v2.13.0 the preference menu is now empty and for some reason after downgrading back to v.2.12, the text in the preference menu looks like **⧼prefs-citizen-theme-option-light⧽** instead of light  or **⧼prefs-citizen-lineheight-label⧽** instead of line height

## System
 - MediaWiki version 1.41.1
 - PHP version 8.2.4 (litespeed)

Thank you!

**Comment by alistair3149** [comment]
There are significant rework on the preference menu and it might be caching that causes both of the issues you mentioned. Do you have any errors in your browser console log?

**Comment by andre-paulo98** [comment]
I installed 2.13.0 on a brand new wiki and I have the same issue.
There's this error in console:
```
addPortlet.polyfill.js:13 Uncaught TypeError: portlet.querySelector is not a function
    at addDefaultPortlet (addPortlet.polyfill.js:13:21)
    at addPortlet (addPortlet.polyfill.js:49:10)
    at resources/skins.citizen.preferences/clientPreferences.js (clientPreferences.js:25:57)
    at require (load.php?lang=en-gb&modules=startup&only=scripts&raw=1&skin=citizen:8:863)
    at HTMLButtonElement.initPanel (skins.citizen.preferences.js:102:29)
addDefaultPortlet @ addPortlet.polyfill.js:13
addPortlet @ addPortlet.polyfill.js:49
resources/skins.citizen.preferences/clientPreferences.js @ clientPreferences.js:25
require @ load.php?lang=en-gb&modules=startup&only=scripts&raw=1&skin=citizen:8
initPanel @ skins.citizen.preferences.js:102
```

**Comment by alistair3149** [comment]
Which version of MediaWiki are you using?

**Comment by alistair3149** [comment]
Please let me know if it fixes it for you!

**Comment by andre-paulo98** [comment]
Different error, but seems like result is the same
 ```
clientPreferences.js:294 Uncaught (in promise) TypeError: addPortlet is not a function
    at makeClientPreference (clientPreferences.js:294:19)
    at clientPreferences.js:335:4
    at Array.forEach (<anonymous>)
    at clientPreferences.js:334:41
    at new Promise (<anonymous>)
    at Object.render (clientPreferences.js:333:9)
    at HTMLButtonElement.initPanel (skins.citizen.preferences.js:120:21)
makeClientPreference @ clientPreferences.js:294
(anonymous) @ clientPreferences.js:335
(anonymous) @ clientPreferences.js:334
render @ clientPreferences.js:333
initPanel @ skins.citizen.preferences.js:120
```

**Comment by alistair3149** [comment]
Would you be able to check if it is fixed now?

**Comment by andre-paulo98** [comment]
works now 👍, thanks! 💖
